"""add dlq tasks

Revision ID: ece9f7da2ffe
Revises: 1bd09c890cba
Create Date: 2026-10-09 15:06:07.539305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ece9f7da2ffe'
down_revision: Union[str, Sequence[str], None] = '1bd09c890cba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dlq_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_key', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_key')
    )
    op.create_index(op.f('ix_dlq_tasks_published_at'), 'dlq_tasks', ['published_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dlq_tasks_published_at'), table_name='dlq_tasks')
    op.drop_table('dlq_tasks')
    # ### end Alembic commands ###
